### ISSUE TITLE
Namespaced properties: cannot resolve type

### ISSUE THREAD

**Issue by ForNeVeR** [elw00d/consoleframework#67]
Consider I have this XAML:

```xaml
<c:Window xmlns:c="clr-namespace:ConsoleFramework.Controls;assembly=ConsoleFramework"
          xmlns:x="clr-namespace:ConsoleFramework.Xaml;assembly=ConsoleFramework"
                MinHeight="10" MinWidth="25"
                X="0" Y="0"
                Title="Refs">
    <c:ListBox VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
        <c:ListBox.Items>
            <string>xxxx</string>
        </c:ListBox.Items>
    </c:ListBox>
</c:Window>
```

When I try to load it, ConsoleFramework throws an exception:
```
Unhandled exception. System.InvalidOperationException: Cannot resolve type c:ListBox.Items
   at Xaml.XamlParser.resolveType(String name)
   at Xaml.XamlParser.createObject(String name)
   at Xaml.XamlParser.createFromXaml(String xaml, Object dataContext)
   at Xaml.XamlParser.CreateFromXaml[T](String xaml, Object dataContext, List`1 defaultNamespaces)
   at Fenrir.Ui.EntryPoint.loadFromXaml[a](String resourceName, RefsViewModel dataContext) in D:\X-Files\Projects\Fenrir\Fenrir.Ui\EntryPoint.fs:line 19
   at Fenrir.Ui.EntryPoint.run(String path) in D:\X-Files\Projects\Fenrir\Fenrir.Ui\EntryPoint.fs:line 28
   at Fenrir.Program.main(String[] argv) in D:\X-Files\Projects\Fenrir\Fenrir\Program.fs:line 187
```

It will work well if I write `<ListBox.Items>` instead of `<c:ListBox.Items>`, but this isn't right!

**Comment by elw00d** [comment]
Try `xmlns:c="http://consoleframework.org/xaml.xsd"` ?

**Comment by igor-kostromin** [comment]
I have copy-pasted your layout and it seems working ok...

Are you using actual `develop` branch ?

**Comment by ForNeVeR** [comment]
I was able to confirm that it was broken in 0.0.3, but is currently fixed in `develop`. Thanks!
